[versions]
recyclerview = "1.4.0"
junit = "4.13.2"
okhttp = "5.4.0"
androidx-test-ext-junit = "1.2.1"
espresso = "3.6.1"
test-runner = "1.6.2"
test-rules = "1.6.1"

[libraries]
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
